// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppgcllbadfpvwzhynsya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwZ2NsbGJhZGZwdnd6aHluc3lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDQ3MjUsImV4cCI6MjA3MjYyMDcyNX0.tajtwkpEJTAuLdMVKqVocuq6GPoW85CGV9wFlnJIYFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});